### PR TITLE
fix(*): incorrect handling of svc tag

### LINKED ISSUE #6: 服务注册时使用了tags，但注册后在consul的meta里
我服务注册时使用了tags，但注册后在consul的meta里
```
func localOption() []server.Option {
	r, err := consul.NewConsulRegister(util.ConsulAddr())
	if err != nil {
		panic(err)
	}
	address, err := net.ResolveTCPAddr("tcp", constant.ServicesAccountServiceAddr)
	if err != nil {
		panic(err)
	}
	return []server.Option{
		server.WithSuite(trace.NewDefaultServerSuite()),
		server.WithServerBasicInfo(&rpcinfo.EndpointBasicInfo{ServiceName: constant.ServicesAccountServiceName}),
		server.WithRegistry(r),
		server.WithRegistryInfo(&registry.Info{
			Addr:        address,
			ServiceName: constant.ServicesAccountServiceName,
			StartTime:   time.Now(),
			Tags: map[string]string{
				"version": "1.0",  // 这边注册tag
			}}),
		server.WithServiceAddr(address),
		server.WithLimit(&limit.Option{MaxConnections: constant.MaxConnections, MaxQPS: constant.MaxQPS}),
	}
}
```
在consul的后台，发现在meta里
image

看了[registry-consul](https://github.com/kitex-contrib/registry-consul/blob/main/consul_registry.go#L93)代码，tag也是当meta使用的

### PR DESCRIPTION
**Pull request by baiyutang**
Fix: #6 

- fix the bug of tag handling
- upgrade kitex version
- makefile optimizing
- unit test 

image

### CODE REVIEW

File: consul_registry.go [hunk 1]
```diff
@@ -1,37 +1,44 @@
...
 }
 
+const kvJoinChar = ":"
+
 var _ registry.Registry = (*consulRegistry)(nil)
 
-type options struct {
-	check *api.AgentServiceCheck
-}
+var errillegalTagChar = errors.New("illegal tag character")
```
Comment (felix021) [inline consul_registry.go]: naming: `errIllegalTagChar`, `I` should be capitalized here.

File: consul_registry.go [hunk 2]
```diff
@@ -81,16 +89,26 @@ func (c *consulRegistry) Register(info *registry.Info) error {
...
 		return err
 	}
+
+	var svcTags []string
+	for k, v := range info.Tags {
+		if strings.Contains(k, kvJoinChar) || strings.Contains(v, kvJoinChar) {
+			return errillegalTagChar
+		}
+		svcTags = append(svcTags, fmt.Sprintf("%s%s%s", k, kvJoinChar, v))
+	}
```
Comment (felix021) [inline consul_registry.go:101]: 1. Better refactor this into a new func with unit tests.
2. slice can be initialized with capacity = len(info.Tags)

File: consul_resolver.go [hunk 3]
```diff
@@ -102,3 +105,27 @@ func (c *consulResolver) Diff(cacheKey string, prev, next discovery.Result) (dis
...
+
+	for _, tag := range tags {
+		strArr := strings.Split(tag, kvJoinChar)
+		switch len(strArr) {
+		case 0:
+			continue
+		case 1:
+			key := strArr[0]
+			tagMap[key] = ""
+		default:
```
Comment (ppzqh) [inline consul_resolver.go]: 为啥这里是default？是否需要判断len>2的情况

File: consul_resolver.go [hunk 4]
```diff
@@ -102,3 +105,27 @@ func (c *consulResolver) Diff(cacheKey string, prev, next discovery.Result) (dis
 func (c *consulResolver) Name() string {
 	return "consul"
 }
+
+func splitTags(tags []string) map[string]string {
```
Comment (felix021) [inline consul_resolver.go:110]: unit test

File: consul_registry.go [hunk 5]
```diff
@@ -81,16 +89,26 @@ func (c *consulRegistry) Register(info *registry.Info) error {
...
 	if err != nil {
 		return err
 	}
+
+	var svcTags []string
+	for k, v := range info.Tags {
+		if strings.Contains(k, kvJoinChar) || strings.Contains(v, kvJoinChar) {
+			return errillegalTagChar
+		}
+		svcTags = append(svcTags, fmt.Sprintf("%s%s%s", k, kvJoinChar, v))
```
Comment (ppzqh) [inline consul_registry.go]: 把这个tag的格式单独抽出来，加一个注释吧

File: consul_registry.go (hunk 2 above)
Comment (felix021) [reply consul_registry.go:101]: And maybe we can weaken the restriction only to keys, as long as we separator "k:v" to only 2 parts.

File: consul_resolver.go [hunk 6]
```diff
@@ -102,3 +105,27 @@ func (c *consulResolver) Diff(cacheKey string, prev, next discovery.Result) (dis
...
+	n := len(tags)
+	tagMap := make(map[string]string, n)
+	if n == 0 {
+		return tagMap
+	}
+
+	for _, tag := range tags {
+		strArr := strings.Split(tag, kvJoinChar)
+		switch len(strArr) {
```
Comment (felix021) [inline consul_resolver.go]: As commented above, if we split "k:v" to only 2 parts according to the first ":", this function will be simpler, and tag without ":" can be treated as illegal input (which should not happen)

File: consul_registry.go (hunk 2 above)
Comment (baiyutang) [reply consul_registry.go:101]: > And maybe we can weaken the restriction only to keys, as long as we separator "k:v" to only 2 parts.

I've thought about it. But I check key illegal char to avoid some bugs. 
For example:
```
registry.Info.Tags = map[string]string{"we:are":"ateam"}
```
Register function, conv it to `[]string{"we:are:ateam"}`
then,Resolve function,how to split it？

File: consul_resolver.go (hunk 3 above)
Comment (baiyutang) [reply consul_resolver.go]: 因为注册信息时我已经严格限定了 tag 的 k / v  不能包含 `:` 的符号，所以这里也就推断到被 `:` 切割的最多有 2 个元素
```
if strings.Contains(k, kvJoinChar) || strings.Contains(v, kvJoinChar) {
			return svcTags, errIllegalTagChar
}
```

File: consul_resolver.go (hunk 6 above)
Comment (baiyutang) [reply consul_resolver.go]: I'm not sure what you mean. 
Above, you told me to weaken the restriction. Here, you suggest to handle two by default.

Logically, only by rigorously validating your input will you be able to rely on it.

另外，如果入参你不限定 value，那被  `:` 切出来之后，可能会有大于 2 个元素的情况。

Comment (felix021) [reply consul_resolver.go]: 我的意思是，只需要限定key没有 ":" 即可；在 split 的时候，根据第一个 ":" 拆分成最多两段（strings.SplitN），不会有歧义，对 value 的限制更少，适用性更好。

File: consul_registry.go (hunk 2 above)
Comment (felix021) [reply consul_registry.go:101]: As I replied in the following conversation, the restriction is only necessary for keys, with which we can always separate "`key`:`value`" into exactly 2 segments, regardless whether values contain ":"

File: consul_resolver.go [hunk 7]
```diff
@@ -102,3 +105,30 @@ func (c *consulResolver) Diff(cacheKey string, prev, next discovery.Result) (dis
...
+		return tagMap
+	}
+
+	for _, tag := range tags {
+		if tag == "" {
+			continue
+		}
+		strArr := strings.SplitN(tag, kvJoinChar, 2)
+		switch len(strArr) {
+		case 1:
```
Comment (felix021) [inline consul_resolver.go]: `len(strArr)` == 1 is also illegal if the tagKV is generated by convTagMapToSlice

**Review by felix021 — APPROVED** [review]

**Review by ppzqh — APPROVED** [review]

**Review by GuangmingLuo — APPROVED** [review]
